# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LUdcanLBJObviTAgPmbPiAQg7mS2U-g
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

df = pd.read_csv("advertising.csv")

print("First 5 rows:")
display(df.head())

X = df[['TV']]   # Simple linear regression
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("\nActual Values:", list(y_test))
print("Predicted Values:", predictions)

print("R² Score:", model.score(X_test, y_test))

plt.scatter(X_test, y_test)
plt.plot(X_test, predictions)
plt.title("TV Advertising vs Sales")
plt.xlabel("TV Advertising")
plt.ylabel("Sales")
plt.show()

