# -*- coding: utf-8 -*-
"""sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKUi0arQglLEcL3IGWdoqVLvaWd56oFy
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("sales_data.csv")

print("First 5 rows:")
display(df.head())

print("\nTotal Sales:", df['sales'].sum())
print("Average Sales:", df['sales'].mean())

region_sales = df.groupby('region')['sales'].sum()
print("\nSales by Region:\n", region_sales)

region_sales.plot(kind='pie', autopct='%1.1f%%')
plt.title("Sales by Region")
plt.ylabel("")
plt.show()

